---

# Check for mysql db
- name: include mysql_db
  include: mysql_db.yml
  when: mysql_db is defined

- name: include mysql_user
  include: mysql_user.yml
  when: mysql_user is defined



- name: include postgres_db
  include: postgresql_db.yml
  when: postgres_db is defined

#- include: postgresql_user.yml