---

# Check for mysql db
- name: include mysql_db
  include: mysql_db.yml
  when: mysql_db is defined

- name: include mysql_user
  include: mysql_user.yml
  when: mysql_user is defined


# Check for postgsql db
#- include: postgresql_db.yml

#- include: postgresql_user.yml